#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export AUTORESEARCH_CACHE_DIR="${AUTORESEARCH_CACHE_DIR:-/root/autodl-tmp/.cache/autoresearch}"
export AUTORESEARCH_BASE_URL="${AUTORESEARCH_BASE_URL:-https://hf-mirror.com/datasets/karpathy/climbmix-400b-shuffle/resolve/main}"
export AUTORESEARCH_MAX_SEQ_LEN="${AUTORESEARCH_MAX_SEQ_LEN:-256}"
export AUTORESEARCH_TIME_BUDGET="${AUTORESEARCH_TIME_BUDGET:-600}"
export AUTORESEARCH_EVAL_TOKENS="${AUTORESEARCH_EVAL_TOKENS:-1048576}"
export AUTORESEARCH_VOCAB_SIZE="${AUTORESEARCH_VOCAB_SIZE:-4096}"
export AUTORESEARCH_DEPTH="${AUTORESEARCH_DEPTH:-6}"
export AUTORESEARCH_ASPECT_RATIO="${AUTORESEARCH_ASPECT_RATIO:-64}"
export AUTORESEARCH_HEAD_DIM="${AUTORESEARCH_HEAD_DIM:-64}"
export AUTORESEARCH_DEVICE_BATCH_SIZE="${AUTORESEARCH_DEVICE_BATCH_SIZE:-64}"
export AUTORESEARCH_TOTAL_BATCH_SIZE="${AUTORESEARCH_TOTAL_BATCH_SIZE:-16384}"
export AUTORESEARCH_WINDOW_PATTERN="${AUTORESEARCH_WINDOW_PATTERN:-L}"
export AUTORESEARCH_ATTN_BACKEND="${AUTORESEARCH_ATTN_BACKEND:-sdpa}"
export AUTORESEARCH_USE_COMPILE="${AUTORESEARCH_USE_COMPILE:-0}"
export AUTORESEARCH_NANOGPT_REF="${AUTORESEARCH_NANOGPT_REF:-1}"
export AUTORESEARCH_REFERENCE_WEIGHT_DECAY="${AUTORESEARCH_REFERENCE_WEIGHT_DECAY:-0.1}"
export AUTORESEARCH_REFERENCE_BETA1="${AUTORESEARCH_REFERENCE_BETA1:-0.9}"
export AUTORESEARCH_REFERENCE_BETA2="${AUTORESEARCH_REFERENCE_BETA2:-0.95}"
export AUTORESEARCH_REFERENCE_DROPOUT="${AUTORESEARCH_REFERENCE_DROPOUT:-0.2}"
export AUTORESEARCH_REFERENCE_BIAS="${AUTORESEARCH_REFERENCE_BIAS:-0}"

mkdir -p runs
PYTHON_BIN=/root/miniconda3/bin/python
if [[ -n "${AUTORESEARCH_LOG_PATH:-}" ]]; then
  mkdir -p "$(dirname "$AUTORESEARCH_LOG_PATH")"
  "$PYTHON_BIN" -m uv run python -m autoresearch_attnres_project.cli "$@" 2>&1 | tee "$AUTORESEARCH_LOG_PATH"
  exit "${PIPESTATUS[0]}"
fi
exec "$PYTHON_BIN" -m uv run python -m autoresearch_attnres_project.cli "$@"
